server:
  port: 9291
spring:
  application:
    name: spring-ai-alibaba-hello
  #配置 大模型地址
  ai:
    openai:
      base-url: http://192.168.101.68:8000
      api-key: qwertyuiop
      chat:
        options:
          model: Qwen3-Coder-30B-A3B-Instruct-5bit