<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jhzhao.alibaba</groupId>
        <artifactId>ai-module</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>spring-ai-alibaba</artifactId>
    <packaging>pom</packaging>

    <name>spring-ai-alibaba</name>
    <modules>
        <module>spring-ai-alibaba-hello</module>
        <module>spring-ai-alibaba-memory</module>
        <module>spring-ai-alibaba-longtermmemory</module>
        <module>spring-ai-alibaba-multimodel</module>
        <module>spring-ai-alibaba-prompt</module>
        <module>spring-ai-alibaba-nacos-prompt</module>
        <module>spring-ai-alibaba-struct-data</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
