server:
  port: 8083

spring:
  application:
    name: auth-center
  # Nacos
  config:
    import:
      - optional:nacos:auth-center.yaml
  cloud:
    nacos:
      server-addr: 172.16.75.107:8848
      username: nacos
      password: nacos
      discovery:
        namespace: dev
        group: DEFAULT_GROUP

