server:
  port: 9091
spring:
  application:
    name: mcp-annotation-client
  main:
    # 禁用Web服务器，使用CLI模式
    web-application-type: none
  #配置 大模型地址
  ai:
    openai:
      base-url: http://192.168.101.49:8000
      api-key: qwertyuiop
      chat:
        options:
          model: GLM-4.7-Flash-4bit
    #    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: qwen3:8b
    mcp:
      client:
        enabled: true
        name: mcp-annotation-client
        version: 1.0.0
        request-timeout: 600s
        type: async
        sse:
          connections:
            server1:
              url: http://localhost:9090
        annotation-scanner:
          enabled: true
