<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jhzhao.alibaba</groupId>
        <artifactId>ai-module</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>spring-ai-module</artifactId>
    <packaging>jar</packaging>

    <name>spring-ai-module</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!--通用的上级的父类的工具-->
        <dependency>
            <groupId>com.jhzhao.alibaba</groupId>
            <artifactId>ai-common</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>

        <!--spring ai 结合使用  ollama 的模型-->
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-ollama</artifactId>
            <version>1.1.2</version>
        </dependency>

        <dependency>
            <groupId>com.jhzhao.alibaba</groupId>
            <artifactId>public-components</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>


    </dependencies>
</project>
